### PR TITLE
widget_slider: // create txt value as original value from the device …

### PR DESCRIPTION
**Pull request by viegener**
…(not via number conversion)

### CODE REVIEW

**Review by knowthelist — COMMENTED** [review]
What are the reasons for that?

**Comment by viegener** [comment]
The current implementation uses the device value converts it into a float (via parsefloat) and then converts this back to a string - so the original text value gets lost and will be shown as NaN (not a number).

Showing a string value from the device is the idea of the "textvalue" class

This was corrected already in the past but obviously got lost...

**Comment by knowthelist** [comment]
Better now? https://github.com/knowthelist/fhem-tablet-ui/commit/29e8551945231d0dd21cb759e042be257c3eeb6b

**Comment by viegener** [comment]
The current implementation uses the device value converts it into a float (via parsefloat) and then converts this back to a string - so the original text value gets lost and will be shown as NaN (not a number).

Showing a string value from the device is the idea of the "textvalue" class

This was corrected already in the past but obviously got lost...

**Comment by viegener** [comment]
Change looks good (not yet tested in my system), so I will close the pull request

**Pull request closed without merging**
